/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as MyBatchesRouteImport } from './routes/my-batches'
import { Route as MyHistoryRouteImport } from './routes/my-history'
import { Route as SelectGoalRouteImport } from './routes/select-goal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBatchesRoute = MyBatchesRouteImport.update({
  id: '/my-batches',
  path: '/my-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHistoryRoute = MyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectGoalRoute = SelectGoalRouteImport.update({
  id: '/select-goal',
  path: '/select-goal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/select-goal': typeof SelectGoalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/select-goal': typeof SelectGoalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/select-goal': typeof SelectGoalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batches' | '/my-batches' | '/my-history' | '/select-goal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batches' | '/my-batches' | '/my-history' | '/select-goal'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/my-batches'
    | '/my-history'
    | '/select-goal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  MyBatchesRoute: typeof MyBatchesRoute
  MyHistoryRoute: typeof MyHistoryRoute
  SelectGoalRoute: typeof SelectGoalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-batches': {
      id: '/my-batches'
      path: '/my-batches'
      fullPath: '/my-batches'
      preLoaderRoute: typeof MyBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-history': {
      id: '/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof MyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-goal': {
      id: '/select-goal'
      path: '/select-goal'
      fullPath: '/select-goal'
      preLoaderRoute: typeof SelectGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  MyBatchesRoute: MyBatchesRoute,
  MyHistoryRoute: MyHistoryRoute,
  SelectGoalRoute: SelectGoalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
