/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as MyBatchesRouteImport } from './routes/my-batches'
import { Route as MyHistoryRouteImport } from './routes/my-history'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PiRouteImport } from './routes/pi'
import { Route as SelectGoalRouteImport } from './routes/select-goal'
import { Route as StoreRouteImport } from './routes/store'
import { Route as BatchBatchIdRouteImport } from './routes/batch.$batchId'
import { Route as TopicsBatchIdSubjectIdRouteImport } from './routes/topics.$batchId.$subjectId'
import { Route as ChapterBatchIdSubjectIdChapterIdRouteImport } from './routes/chapter.$batchId.$subjectId.$chapterId'
import { Route as PdfBatchIdSubjectIdScheduleIdRouteImport } from './routes/pdf.$batchId.$subjectId.$scheduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBatchesRoute = MyBatchesRouteImport.update({
  id: '/my-batches',
  path: '/my-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHistoryRoute = MyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectGoalRoute = SelectGoalRouteImport.update({
  id: '/select-goal',
  path: '/select-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batchId',
  path: '/batch/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsBatchIdSubjectIdRoute = TopicsBatchIdSubjectIdRouteImport.update({
  id: '/topics/$batchId/$subjectId',
  path: '/topics/$batchId/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterBatchIdSubjectIdChapterIdRoute =
  ChapterBatchIdSubjectIdChapterIdRouteImport.update({
    id: '/chapter/$batchId/$subjectId/$chapterId',
    path: '/chapter/$batchId/$subjectId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PdfBatchIdSubjectIdScheduleIdRoute =
  PdfBatchIdSubjectIdScheduleIdRouteImport.update({
    id: '/pdf/$batchId/$subjectId/$scheduleId',
    path: '/pdf/$batchId/$subjectId/$scheduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/offline': typeof OfflineRoute
  '/pi': typeof PiRoute
  '/select-goal': typeof SelectGoalRoute
  '/store': typeof StoreRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/topics/$batchId/$subjectId': typeof TopicsBatchIdSubjectIdRoute
  '/chapter/$batchId/$subjectId/$chapterId': typeof ChapterBatchIdSubjectIdChapterIdRoute
  '/pdf/$batchId/$subjectId/$scheduleId': typeof PdfBatchIdSubjectIdScheduleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/offline': typeof OfflineRoute
  '/pi': typeof PiRoute
  '/select-goal': typeof SelectGoalRoute
  '/store': typeof StoreRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/topics/$batchId/$subjectId': typeof TopicsBatchIdSubjectIdRoute
  '/chapter/$batchId/$subjectId/$chapterId': typeof ChapterBatchIdSubjectIdChapterIdRoute
  '/pdf/$batchId/$subjectId/$scheduleId': typeof PdfBatchIdSubjectIdScheduleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/my-batches': typeof MyBatchesRoute
  '/my-history': typeof MyHistoryRoute
  '/offline': typeof OfflineRoute
  '/pi': typeof PiRoute
  '/select-goal': typeof SelectGoalRoute
  '/store': typeof StoreRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/topics/$batchId/$subjectId': typeof TopicsBatchIdSubjectIdRoute
  '/chapter/$batchId/$subjectId/$chapterId': typeof ChapterBatchIdSubjectIdChapterIdRoute
  '/pdf/$batchId/$subjectId/$scheduleId': typeof PdfBatchIdSubjectIdScheduleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/my-batches'
    | '/my-history'
    | '/offline'
    | '/pi'
    | '/select-goal'
    | '/store'
    | '/batch/$batchId'
    | '/topics/$batchId/$subjectId'
    | '/chapter/$batchId/$subjectId/$chapterId'
    | '/pdf/$batchId/$subjectId/$scheduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/my-batches'
    | '/my-history'
    | '/offline'
    | '/pi'
    | '/select-goal'
    | '/store'
    | '/batch/$batchId'
    | '/topics/$batchId/$subjectId'
    | '/chapter/$batchId/$subjectId/$chapterId'
    | '/pdf/$batchId/$subjectId/$scheduleId'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/my-batches'
    | '/my-history'
    | '/offline'
    | '/pi'
    | '/select-goal'
    | '/store'
    | '/batch/$batchId'
    | '/topics/$batchId/$subjectId'
    | '/chapter/$batchId/$subjectId/$chapterId'
    | '/pdf/$batchId/$subjectId/$scheduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  MyBatchesRoute: typeof MyBatchesRoute
  MyHistoryRoute: typeof MyHistoryRoute
  OfflineRoute: typeof OfflineRoute
  PiRoute: typeof PiRoute
  SelectGoalRoute: typeof SelectGoalRoute
  StoreRoute: typeof StoreRoute
  BatchBatchIdRoute: typeof BatchBatchIdRoute
  TopicsBatchIdSubjectIdRoute: typeof TopicsBatchIdSubjectIdRoute
  ChapterBatchIdSubjectIdChapterIdRoute: typeof ChapterBatchIdSubjectIdChapterIdRoute
  PdfBatchIdSubjectIdScheduleIdRoute: typeof PdfBatchIdSubjectIdScheduleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-batches': {
      id: '/my-batches'
      path: '/my-batches'
      fullPath: '/my-batches'
      preLoaderRoute: typeof MyBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-history': {
      id: '/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof MyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-goal': {
      id: '/select-goal'
      path: '/select-goal'
      fullPath: '/select-goal'
      preLoaderRoute: typeof SelectGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId': {
      id: '/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$batchId/$subjectId': {
      id: '/topics/$batchId/$subjectId'
      path: '/topics/$batchId/$subjectId'
      fullPath: '/topics/$batchId/$subjectId'
      preLoaderRoute: typeof TopicsBatchIdSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$batchId/$subjectId/$chapterId': {
      id: '/chapter/$batchId/$subjectId/$chapterId'
      path: '/chapter/$batchId/$subjectId/$chapterId'
      fullPath: '/chapter/$batchId/$subjectId/$chapterId'
      preLoaderRoute: typeof ChapterBatchIdSubjectIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$batchId/$subjectId/$scheduleId': {
      id: '/pdf/$batchId/$subjectId/$scheduleId'
      path: '/pdf/$batchId/$subjectId/$scheduleId'
      fullPath: '/pdf/$batchId/$subjectId/$scheduleId'
      preLoaderRoute: typeof PdfBatchIdSubjectIdScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  MyBatchesRoute: MyBatchesRoute,
  MyHistoryRoute: MyHistoryRoute,
  OfflineRoute: OfflineRoute,
  PiRoute: PiRoute,
  SelectGoalRoute: SelectGoalRoute,
  StoreRoute: StoreRoute,
  BatchBatchIdRoute: BatchBatchIdRoute,
  TopicsBatchIdSubjectIdRoute: TopicsBatchIdSubjectIdRoute,
  ChapterBatchIdSubjectIdChapterIdRoute: ChapterBatchIdSubjectIdChapterIdRoute,
  PdfBatchIdSubjectIdScheduleIdRoute: PdfBatchIdSubjectIdScheduleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
